version: '3.8'

services:
  # HDFS NameNode (Web UI: 9870)
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ../data:/data
    networks:
      - hadoop

  # HDFS DataNode 1
  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SERVICE_PRECONDITION=namenode:9870
    depends_on:
      - namenode
    volumes:
      - ../data:/data
    networks:
      - hadoop

  # HDFS DataNode 2
  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SERVICE_PRECONDITION=namenode:9870
    depends_on:
      - namenode
    volumes:
      - ../data:/data
    networks:
      - hadoop
  # YARN ResourceManager (Web UI: 8088)
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    ports:
      - "8088:8088"
    depends_on:
      - namenode
    networks:
      - hadoop

  # NodeManager 1
  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager1
    depends_on:
      - resourcemanager
    networks:
      - hadoop

  # NodeManager 2
  nodemanager2:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager2
    depends_on:
      - resourcemanager
    networks:
      - hadoop

  # Spark Master (Web UI: 8080)
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark
    ports:
      - "8080:8080"
      - "7077:7077"   # spark master port
    volumes:
      - ..:/workspace
    networks:
      - hadoop
    depends_on:
      - resourcemanager

  # Spark Worker 1 (Web UI: 8081)
  spark-worker1:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker1
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8081:8081"
    volumes:
      - ..:/workspace
    networks:
      - hadoop
    depends_on:
      - spark-master

  # Spark Worker 2 (Web UI: 8082)
  spark-worker2:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker2
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8082:8082"
    volumes:
      - ..:/workspace
    networks:
      - hadoop
    depends_on:
      - spark-master

networks:
  hadoop:
    driver: bridge
